### ISSUE TITLE
3D-Secure redirect - Configuration not restored after Activity is resumed "Unable to resume activity DropInActivity"

### ISSUE THREAD

**Issue by koh-osug** [braintree/braintree_android#181]
### General information

* Drop In Ui version 3.20
* Braintree 2.8.1
* Environment: Debug Mode
* Android Version and Device: Infinix Zero 3 with Android 6.0

### Issue description

The user is redirected to a 3D-Secure page and later returns to the Drop In UI activity. The activity is crashing the app.
The Android life cycle is not properly implemented. When the Drop-In UI activity is destroyed and should be resumed the configuration seems to be lost. This can be simulated when going to Developer Options -> "Don't keep activities". This destroys the activity.

```
E/UncaughtException: java.lang.RuntimeException: Unable to resume activity {com.simless.app/com.braintreepayments.api.dropin.DropInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.braintreepayments.api.models.Configuration.isThreeDSecureEnabled()' on a null object reference
                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3269)
                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3300)
                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2614)
                         at android.app.ActivityThread.-wrap11(ActivityThread.java)
                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1465)
                         at android.os.Handler.dispatchMessage(Handler.java:111)
                         at android.os.Looper.loop(Looper.java:207)
                         at android.app.ActivityThread.main(ActivityThread.java:5683)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.braintreepayments.api.models.Configuration.isThreeDSecureEnabled()' on a null object reference
                         at com.braintreepayments.api.dropin.BaseActivity.shouldRequestThreeDSecureVerification(BaseActivity.java:50)
                         at com.braintreepayments.api.dropin.DropInActivity.onPaymentMethodNonceCreated(DropInActivity.java:202)
                         at com.braintreepayments.api.BraintreeFragment$4.run(BraintreeFragment.java:577)
                         at com.braintreepayments.api.BraintreeFragment.flushCallbacks(BraintreeFragment.java:684)
                         at com.braintreepayments.api.BraintreeFragment.addListener(BraintreeFragment.java:397)
                         at com.braintreepayments.api.BraintreeFragment.onResume(BraintreeFragment.java:236)
                         at android.app.Fragment.performResume(Fragment.java:2279)
                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1013)
                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1135)
                         at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1990)
                         at android.app.FragmentController.dispatchResume(FragmentController.java:174)
                         at android.app.Activity.performResume(Activity.java:6366)
                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3254)
                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3300) 
                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2614) 
                         at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1465) 
                         at android.os.Handler.dispatchMessage(Handler.java:111) 
                         at android.os.Looper.loop(Looper.java:207) 
                         at android.app.ActivityThread.main(ActivityThread.java:5683) 
                         at java.lang.reflect.Method.invoke(Native Method) 
                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
D/SQLiteDatabase: Open database
                  java.lang.Throwable: stacktrace
                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:815)
                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:576)
                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
                      at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                      at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                      at com.braintreepayments.api.internal.AnalyticsDatabase$1.run(AnalyticsDatabase.java:74)
                      at com.braintreepayments.api.internal.AnalyticsDatabase$DatabaseTask.doInBackground(AnalyticsDatabase.java:187)
                      at com.braintreepayments.api.internal.AnalyticsDatabase$DatabaseTask.doInBackground(AnalyticsDatabase.java:176)
                      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.simless.app, PID: 17272
                  java.lang.RuntimeException: Unable to resume activity {com.simless.app/com.braintreepayments.api.dropin.DropInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.braintreepayments.api.models.Configuration.isThreeDSecureEnabled()' on a null object reference
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3269)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3300)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2614)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1465)
                      at android.os.Handler.dispatchMessage(Handler.java:111)
                      at android.os.Looper.loop(Looper.java:207)
                      at android.app.ActivityThread.main(ActivityThread.java:5683)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.braintreepayments.api.models.Configuration.isThreeDSecureEnabled()' on a null object reference
                      at com.braintreepayments.api.dropin.BaseActivity.shouldRequestThreeDSecureVerification(BaseActivity.java:50)
                      at com.braintreepayments.api.dropin.DropInActivity.onPaymentMethodNonceCreated(DropInActivity.java:202)
                      at com.braintreepayments.api.BraintreeFragment$4.run(BraintreeFragment.java:577)
                      at com.braintreepayments.api.BraintreeFragment.flushCallbacks(BraintreeFragment.java:684)
                      at com.braintreepayments.api.BraintreeFragment.addListener(BraintreeFragment.java:397)
                      at com.braintreepayments.api.BraintreeFragment.onResume(BraintreeFragment.java:236)
                      at android.app.Fragment.performResume(Fragment.java:2279)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1013)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1135)
                      at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1990)
                      at android.app.FragmentController.dispatchResume(FragmentController.java:174)
                      at android.app.Activity.performResume(Activity.java:6366)
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3254)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3300) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2614) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1465) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:207) 
                      at android.app.ActivityThread.main(ActivityThread.java:5683) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
```

**Comment by crookedneighbor** [comment]
Thanks for the report, we'll look into this.

**Comment by crookedneighbor** [comment]
Also, in the future if you find a bug in Drop-in, there's a separate repo for it: https://github.com/braintree/braintree-android-drop-in

**Comment by koh-osug** [comment]
Ok, you are free to move it to this repo.

**Comment by koh-osug** [comment]
Is there a patch plan where to await a fix for this? It seems we are serving several low end devices, which are killing the activity on context switches to due low memory situation. Most likely this is happening when the user is looking up the 3DS secret, e.g. in the SMS application and returns to the drop-in UI.

**Comment by demerino** [comment]
@koh-osug Apologies for the delay. We're working on a fix for this and hope to have it available soon.

**Comment by bluk** [comment]
This should be fixed in [Android Drop-in 3.2.1](https://github.com/braintree/braintree-android-drop-in/releases/tag/3.2.1). Thanks.

**Comment by koh-osug** [comment]
I get now the error: "Nonce is already 3D Secure" when the activity is recreated after returning from 3DS. There seems to be still an issue.

**Comment by koh-osug** [comment]
I have not updated the library until now because I was not aware that you fixed this. Was the issue solved?

**Comment by crookedneighbor** [comment]
This should be fixed now. Can you update and try again?

Going to close this for now, but I'll open it again if you're still having issues.

**Comment by koh-osug** [comment]
What version is containing the fix? Do you have a reference to the change set in GitHub to follow the patch?

**Comment by crookedneighbor** [comment]
The latest, 3.4.0 https://github.com/braintree/braintree-android-drop-in/blob/master/CHANGELOG.md#340 which includes an update to the underlying android sdk which has a 3ds fix: https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#2131
